# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

# pool:
#   vmImage: 'ubuntu-latest'

stages:
- stage: Stage1_Install_Dependencies
  jobs: 
    - job: job1_Install_NodeJS
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

- stage: Stage2_Build_Apps
  jobs: 
    - job: job1_Deploy_Smart_Contract
      steps: 
      - script: | 
          cd ./quorum
          npm install
          npx truffle migrate --reset --network bankBuyerSeller
          cp -r ../quorum ../webapp/bank
          cp -r ../quorum ../webapp/buyer
          cp -r ../quorum ../webapp/seller
        displayName: "Deploy Smart Contracts"
      
    - job: job2_Build_Backend_Apps
      steps: 
      - script: |
          cp ./web3Setup.js ./webapp/lib/web3
          cp -r ./webapp/lib/config ./webapp/bank
          cp -r ./webapp/lib/web3 ./webapp/bank
          cd ./webapp/bank
          ls -al
          cat ./web3/web3Setup.js
          npm install
        displayName: 'NPM install for bank'

      - script: |
          cp ./web3Setup.js ./webapp/lib/web3
          cp -r ./webapp/lib/config ./webapp/buyer
          cp -r ./webapp/lib/web3 ./webapp/buyer
          cd ./webapp/buyer
          ls -al
          cat ./web3/web3Setup.js
          npm install
        displayName: 'NPM install for buyer'

      - script: |
          cp ./web3Setup.js ./webapp/lib/web3
          cp -r ./webapp/lib/config ./webapp/seller
          cp -r ./webapp/lib/web3 ./webapp/seller
          cd ./webapp/seller
          ls -al
          cat ./web3/web3Setup.js
          npm install
        displayName: 'NPM install for seller'

- stage: Stage3_Clean_Artifacts
  jobs:
    - job: job1_Clean_Artifacts
      steps: 
      - script: |
          rm -rf *.yml
          rm -rf *.md
          rm .gitignore
          rm -rf *.sh
          rm .gitignore
          rm -rf ./quorum
          rm ./web3Setup.js
          rm -rf ./webapp/lib
          rm ./webapp/package.json
          ls -al
        displayName: "Remove unnecessary files"
    
    - job: job2_Publish_Artifacts
      steps:
      - publish: $(System.DefaultWorkingDirectory)/
        artifact: WebApp
        displayName: 'Publish artifact'